### ISSUE TITLE
Non-breaking spaces being encoded as `&nbsp;` even with `encodeEntities: 'utf8'`

### ISSUE THREAD

**Issue by ehamberg** [cheeriojs/dom-serializer#1122]
This might very well be me misunderstanding something, but I expected a non-breaking space (U+00a0) to _not_ be encoded as `&nbsp;` when specifying `encodeEntities: 'utf8'`. Is this intended behaviour?

**Comment by fb55** [comment]
`utf8` stops characters from outside the ASCII range to be encoded as well. I agree that the wording is not great, happy to accept PRs.
