### ISSUE TITLE
special HTML / XML characters are not encoded if decodeEntities is false

### ISSUE THREAD

**Issue by aurelienlt** [cheeriojs/dom-serializer#26]
Hi. I'm having trouble with the HTML source generation using cheerio (thus using the dom-serializer). If I generate the source using `.html()`, then any UTF8 character is encoded, making a pretty uselessly long output. But if I use `.html({decodeEntities: false})`, then HTML special characters are not encoding, producing an invalid source, open to code injection.

```
var cheerio = require("cheerio");
var $ = cheerio.load('<p name="&quote;éé&amp;èè&quote;">&lt;ééèè&gt;</p>');
// over-encoded, UTF-8 characters are encoding which makes an heavier output
console.log($.html({decodeEntities: true}))
// under-encoded, the output is not a valid HTML document
console.log($.html({decodeEntities: false}))
```

These few characters should ALWAYS be encoded as it is first required by the standards, and second it oswerwise leaves an open door to any code injection (including javascript injection) to the code.

**Comment by fb55** [comment]
Unfortunately this works as intended.
