### ISSUE TITLE
Parsin in XML mode does not properly parse unencoded HTML entities contained within a tag 

### ISSUE THREAD

**Issue by gajus** [cheeriojs/dom-serializer#281]
```js
const $ = cheerio.load('<script id="data-layer">"<br>"</script>', {
  xmlMode: true
});

console.log($.html());

```

Produces:

```
<script id="data-layer">"<br>&quot;</br></script>

```

Expected:

```
<script id="data-layer">"<br>"</script>

```

Cheerio version: ^1.0.0-rc.2

**Comment by fb55** [comment]
With `xmlMode` on, the expected output for the example above is `"<script>&quot;<br>&quot;</br></script>"`. There was a bug that prevented the first quote to not be encoded. This has been fixed in #282. I've also added a test to demonstrate how this works as expected outside of `xmlMode`.
