### ISSUE TITLE
Root nodes not being properly rendered due to dependancy issue

### ISSUE THREAD

**Issue by gbrlmtrz** [cheeriojs/dom-serializer#396]
Hey everyone! I've found that this library is using domelementypes.root. For example in here

https://github.com/cheeriojs/dom-serializer/blob/36e7bd414eca6429fb0e62ec038b7d9a2273f69b/src/index.ts#L141

And I've also noticed that this repo is using domelementtype v2.0.1 (https://github.com/cheeriojs/dom-serializer/blob/36e7bd414eca6429fb0e62ec038b7d9a2273f69b/package.json#L22) which is kinda weird because that type doesn't exist in that version of that lib https://github.com/fb55/domelementtype/blob/v2.0.1/src/index.ts

I'm creating this issue because currently that is kinda breaking some builds I've been trying to deploy, but maybe that is my own issue with yarn... Regardless, maybe a bump for this version would be a quick fix for it? 

Thanks!

**Comment by fb55** [comment]
The `package-lock.json` file shows that the `domelementtypes` version is resolved as `2.2.0`. It looks like your tooling isn't picking up that file?

Happy to accept a PR that bumps the version in the `package.json`, should that help.

**Comment by fb55** [comment]
Assuming this has been resolved.

**Comment by alloystory** [comment]
nope this has not been solved. updating the package.json worked for me. i submitted a PR for this
