### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by edi9999** [cheeriojs/dom-serializer#55]
Hello, can you please publish a new version to npm ?

In the previous version, you were depending on domelementtype 1.1.1 explicitly, which didn't have a license file published to npm. In the current domelementtype version  (1.3.0), the license file has been published too.

Can you please publish a new minor version 0.1.1 ?

Thanks in advance.

**Comment by nazar-pc** [comment]
Yes, please.
Other packages require domelementtype 1.3 and because I'm installing it with https://github.com/fxpio/composer-asset-plugin I really need to resolve dependencies to single version (my target package is `slate`, which contains this package somewhere deep in dependencies nightmare).

**Comment by TremayneChrist** [comment]
+1

**Comment by TremayneChrist** [comment]
@fb55 ?

**Comment by nickraphael** [comment]
I'm guessing this is still an issue years later?

**Comment by davezuko** [comment]
Running into the same issue. Any chance this could be published? Thanks!
