### ISSUE TITLE
TypeError: render is not a function in ES module, but not in CJS module

### ISSUE THREAD

**Issue by robogeek** [cheeriojs/dom-serializer#576]
I've examined the source code and see "export default function render", and I understand the example code you give.   If I implement the example in an ES module, I get the error message shown above, but if implemented in a CJS module, it successfully deserializes the DOM into HTML.

```
$ node --version
v16.13.0
```

The host is macOS 10.15.7 (Catalina).

Using the ES module, I get this output:

```
{ default: [Function: render] }
{ default: [Function: render] }
file:///Volumes/Extra/ws/techsparx.com/projects/node.js/htmlparser2/test2.mjs:30
const serilzd = render(dom);
                ^

TypeError: render is not a function
    at file:///Volumes/Extra/ws/techsparx.com/projects/node.js/htmlparser2/test2.mjs:30:17
```

The first two lines are me printing out the `render` object to make sure what module object was retrieved.  The full source code is below.  I've tried several variants to the program, and I keep getting this message.

Transliterating the same code into a CJS module, it instead executes successfully.  The `serilzd` variable gets the expected HTML text string which I can print out.

```js
import { default as htmlparser2, Parser } from "htmlparser2";
import { DomHandler } from "domhandler";
import { default as render } from "dom-serializer";
import { default as fs, promises as fsp } from 'fs';
import util from 'util';

const rawHtml = await fsp.readFile(process.argv[2], 'utf8');

const dom = htmlparser2.parseDocument(rawHtml);

console.log(dom);

console.log(render);
console.log(util.inspect(render));

const serilzd = render(dom);

console.log(serilzd);
```

This is the ES module version

```js

const htmlparser2 = require('htmlparser2');
const render = require('dom-serializer').default;
const fs = require('fs');
const fsp = require('fs').promises;
const util = require('util');

(async () => {

    const rawHtml = await fsp.readFile(process.argv[2], 'utf8');

    const dom = htmlparser2.parseDocument(rawHtml);
    
    console.log(dom);
    
    console.log(render);
    console.log(util.inspect(render));
    
    const serilzd = render(dom);
    
    console.log(serilzd);
    
})().catch(err => {
    console.error(err);
});
```

This is the CJS module version

**Comment by robogeek** [comment]
FYI - I tried running the examples on Node.js 14 and got the same behavior as on Node.js 16

**Comment by fb55** [comment]
Hi @robogeek, this module is still targeting commonjs. TypeScript compiles the import statements to `requires`. Hope this makes sense!

**Comment by robogeek** [comment]
Thank you for your reply.  I've used CJS modules a lot in ES6 modules, and not seen a problem like this.

**Comment by Frank-Mayer** [comment]
I have fixed this here: [github.com/Frank-Mayer/dom-serializer](https://github.com/Frank-Mayer/dom-serializer)

`yarn add @frank-mayer/dom-serializer`

**Comment by fb55** [comment]
@Frank-Mayer What exactly did you fix? Happy to accept PRs!

**Comment by Frank-Mayer** [comment]
@fb55 https://github.com/cheeriojs/dom-serializer/pull/631
