### ISSUE TITLE
https://github.com/cheeriojs/dom-serializer/blob/master/index.js  for loop needs if(hasOwnProperty)

### ISSUE THREAD

**Issue by izdesenko** [cheeriojs/dom-serializer#70]
please wrap body of fomatAttrs for loop into "if(...hasOwnProperty(...))" condition. Otherwise formatAttrs tries to render my Object.prototype methods :(

here is direct link: https://github.com/cheeriojs/dom-serializer/blob/master/index.js#L29

**Comment by fb55** [comment]
You should use non-enumerable properties to extend `Object.prototype`. Have a look at `Object.define` to do that.
