### ISSUE TITLE
Issue with quotes

### ISSUE THREAD

**Issue by ArmorDarks** [cheeriojs/dom-serializer#71]
There is an issue with quotes — serializer always forces them to be double quotes and completely neglects initial input. It should preserve single quotes in attributes.

This is a source for an issue of cheerio, described here: https://github.com/cheeriojs/cheerio/issues/1006

**Comment by ArmorDarks** [comment]
@fb55? Anyone? Is it still maintained?

**Comment by dickeylth** [comment]
+1 call for help!
https://github.com/cheeriojs/cheerio/issues/720#issuecomment-269178894

**Comment by fb55** [comment]
Afaict, this is only an issue with `decodeEntities: false`, which works as intended (even if this is admittedly annoying). Please note that Cheerio is no longer using this project for HTML, so your issue might already be fixed.
