### ISSUE TITLE
selfClosingTags work differently than advertised

### ISSUE THREAD

**Issue by BenWiederhake** [cheeriojs/dom-serializer#727]
Hi there, thanks for making dom-serializer available, I'm looking forward to using it for years to come.

I encountered a weird issue around self-closing tags: The Readme clearly states:
`example With selfClosingTags: true: <foo />`
This is the specific scenario I'm in: I have HTML which may include "weird" tag names like `foo` or `ac:link`, and want the resulting HTML to include self-closing tags like `<foo />`. Note the space before the `/>`.

However, the actual implementation only allows self-closing tags *only* for certain well-known tagnames:
https://github.com/cheeriojs/dom-serializer/blob/5a052077b2c2888e726427ed83a1648c0fdb6d35/src/index.ts#L228

Minimal reproducer:
```
'use strict';

const htmlparser2 = require('htmlparser2');
const render = require('dom-serializer').default;

const myString = '<foo />';
const myDocument = htmlparser2.parseDocument(myString);
const myStringAgain = render(myDocument, {'selfClosingTags': true});
console.log(`${myString}\nbecomes:\n${myStringAgain}`);
```

Expected output:
```
<foo />
becomes:
<foo></foo>
```
(i.e. round-trip identical)

Actual output:
```
<foo />
becomes:
<foo></foo>
```

Suggestions:
- Ideally, I'd like a new options, either to enforce self-closing tags independently of the hard-coded list, or a way to add to the list.
- Or, perhaps, just clear up the documentation that this doesn't actually mean self-closing tags, but rather "self-closing tags but only for those that are a well-know part of HTML", which, eh, I don't know.

**Comment by fb55** [comment]
Hi @BenWiederhake, thanks for reporting this! The goal for the implementation was to provide documents that could be parsed by HTML and XML parsers (see #77 for more details). HTML parsers ignore self-closing tags, so only HTML void elements (self-closing tags) can be self-closing to preserve semantics.

The answer here is that the documentation should be updated, to distinguish `selfClosingTags` with and without `xmlMode: true`.
