### ISSUE TITLE
v0.2.1: UglifyJs throws Unexpected token: keyword «const» in /node_modules/dom-serializer/index.js:108,0

### ISSUE THREAD

**Issue by rupindr** [cheeriojs/dom-serializer#83]
UglifyJs throws Unexpected token: keyword «const» in /node_modules/dom-serializer/index.js:108,0

Due to which react build is failing with following error:

```npm ERR! code ELIFECYCLE
npm ERR! errno 2

...

13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)```

**Comment by rupindr** [comment]
Created a pull request with the fix: https://github.com/cheeriojs/dom-serializer/pull/84

**Comment by timothympace** [comment]
This PR was accepted, but there isn't a new package published to npm yet. Will that be coming soon?

**Comment by joe06102** [comment]
Would you publish a new version including this fix? Thx

**Comment by ddcq** [comment]
I can't wait for a patched version. I temporary use an ES6 compatible version of uglify : https://www.npmjs.com/package/uglify-js-es6#harmony

**Comment by giovannipiller** [comment]
Any plans to publish a new version to NPM including this fix?
Right now, dom-serializer@0.2.1 creates issues when using UglifyJS (non-ES6).

Thanks! 🙇

**Comment by joe06102** [comment]
> Any plans to publish a new version to NPM including this fix?
> Right now, dom-serializer@0.2.1 creates issues when using UglifyJS (non-ES6).
> 
> Thanks! 🙇

I fixed this by including this module in babel and then everything will be under your control!

**Comment by adir-n** [comment]
Any update?
Can you please publish a new version to NPM?

I'm also using UglifyJS (non-ES6) and not using babel.

Thanks!

**Comment by whirmill** [comment]
Any updates about the new release?

For those looking for a temporary workaround, check this:
https://github.com/cheeriojs/dom-serializer/pull/84#issuecomment-545537727
