### ISSUE TITLE
improve readme with motivation

### ISSUE THREAD

**Issue by eoghanmurray** [cheeriojs/dom-serializer#86]
I came across this repository from a random search.

Could the README be improved to mention why this is better than `elem.outerHTML || elem.nodeValue` ?

Maybe the usecase is server and not in a DOM context; if so that'd be good to know!

**Comment by fb55** [comment]
> Maybe the usecase is server and not in a DOM context; if so that'd be good to know!

That's the case. Happy to accept PRs!

**Comment by eoghanmurray** [comment]
Sorry I've no idea what the 'motivation' should say!

I.e. the most I know is to add the following line to the readme:

"Renders a DOM node or an array of DOM nodes to a string.
Useful in a server context where browser DOM functions such as `elem.outerHTML` or `elem.nodeValue` are not available."
