### ISSUE TITLE
Version 0.2.1 has broken Jest tests

### ISSUE THREAD

**Issue by mzedeler** [cheeriojs/dom-serializer#87]
When testing with Jest and enzyme, I get this:

  ● Test suite failed to run

    TypeError: Cannot set property '__proto__' of undefined

      at Object.<anonymous> (node_modules/dom-serializer/index.js:12:37)

**Comment by mzedeler** [comment]
It seems that the two modules that this module depends on have switched to load a data file from `json`, but for some reason, the load fails silently.

**Comment by fb55** [comment]
Seems like this has been solved!
