### ISSUE TITLE
Object.prototype.__proto__ is Deprecated

### ISSUE THREAD

**Issue by charlesverge** [cheeriojs/dom-serializer#88]
Object.prototype.__proto__ is deprecated and it's not clear why it is set to null.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

**Comment by charlesverge** [comment]
https://github.com/cheeriojs/dom-serializer/pull/89

**Comment by fb55** [comment]
Fixed on master.
